### ISSUE TITLE
sslip module needed.

### ISSUE THREAD

**Issue by sgalaburda** [ironport/shrapnel#33]
Hello Guys,

I found that sslip module (wrapper for the OpenSSL library) is missing in the shrapnel code tree.  Because of this fact the coroutine/coro_ssl.py module is broken and I cannot use SSL connections with shrapnel.   If the module was forgotten when shrapnel went open source please add it.  If it was decided not to post the sslip here for some reason please let me know.

Thanks.

**Comment by samrushing** [comment]
sslip was replaced with coro.ssl.openssl
